env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/base'
  - 'plugin:vue/vue3-essential'
  - 'plugin:vue/vue3-strongly-recommended'
  - 'plugin:vue/vue3-recommended'
  - google
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {
  quotes: [ 'error', 'single' ],
}
