version: "3.8"
services:
  proxy:
    container_name: app-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - UI_URL=http://host.docker.internal:8080
      - CLOUD_URL=https://identity-gateway-18ny3umf.uc.gateway.dev
    restart: always
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "80:443" # TODO: Get 443 working