name: Feature Branch

on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  Test:
    name: 'Test Vite App'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v2
      - name: Setup Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Test App
        run: |
          npx vitest run --coverage
          npm run lint
  Build:
    name: 'Build Vite App'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v2
      - name: Setup Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Build App
        run: npx vite build
